# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[default]
src = 'src'
out = 'out'
libs = ['lib']
solc = '0.8.15'
eth-rpc-url = 'https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161'
block_number = 14668845 # Apr - 27 - 2021
